name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Cache poetry
      uses: actions/cache@v1
      with:
        path: ~/.poetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-poetry-1.0.2 # needs manual eviction
    - name: Cache poetry env
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Set up dependencies
      run: |
        wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python3 get-poetry.py --version 1.0.2
        ~/.poetry/bin/poetry install
    - name: Check pyfiles
      run: ~/.poetry/bin/poetry run make check